SAMPLE_ARTICLE_TEXT = """
NASA'S JAMES WEBB SPACE TELESCOPE UNVEILS GORGEOUS AND UNPRECEDENTED VIEWS OF DISTANT STAR-FORMING REGION

The National Aeronautics and Space Administration (NASA) has released a spectacular new series of high-resolution images captured by the James Webb Space Telescope (JWST). These groundbreaking observations offer scientists and astronomy enthusiasts around the world an unprecedented, close-up look at a highly active star-forming region located approximately 390 light-years away in the Ophiuchus cloud complex.

According to astronomical researchers, this nearest star-forming region contains about 50 young stars, all of them similar in mass to our Sun, or smaller. The stunning images reveal cosmic jets of hydrogen gas blasting from newborn stars, which light up the surrounding interstellar dust and create jaw-dropping glowing cavities. "Webb's image of Ophiuchus allows us to witness a very brief phase in the stellar life cycle with extreme clarity. Our own Sun experienced a phase like this, long ago, and now we have the technology to see the beginning of another star's story," said Dr. Jane Rigby, a senior astrophysicist at NASA's Goddard Space Flight Center.

The data gathered from Webb is already changing our understanding of how stars and planetary systems form. Traditional space telescopes were unable to penetrate the thick layers of cosmic dust shrouding these young protostars. Thanks to JWST's highly sensitive Near-Infrared Camera (NIRCam) and Mid-Infrared Instrument (MIRI), scientists can now peer directly through the dust to analyze the chemical composition and physical properties of the infant stars. Scientists discovered rich reservoirs of organic compounds and water ice in the protoplanetary disks, indicating that the chemical building blocks of life are present from the very birth of a star system.

In addition to the scientific breakthroughs, the images themselves are a visual masterpiece, showcasing cascading curtains of crimson dust, brilliant blue stellar highlights, and intricate structures of gas. Space enthusiasts have praised the images as some of the most beautiful pictures ever captured of the cosmos, sparking a wave of public interest in modern space exploration. NASA plans to continue its observations of the Ophiuchus cloud complex over the next several months, with the hope of detecting early signs of planet formation within the circumstellar disks.
"""
